<template>    
    <select id="nationNo" name="nationNo" class="sel" aria-label="전화번호 입력"  v-model="selected">
      <option v-for="item in nationNmber" :value="item.value">
        {{item.text}}
      </option>
    </select>
</template>

<script>
export default {
    data(){
        return {
            selected: '82',
            nationNmber: [
                {text:"가나 +233", value: "233"},
                {text:"가봉 +241", value: "241"},
                {text:"가이아나 +592", value: "592"},
                {text:"감비아 +220", value: "220"},
                {text:"과테말라 +502", value: "502"},
                {text:"괌 +1 671", value: "1671"},
                {text:"그레나다 +1 473", value: "1473"},
                {text:"그리스 +30", value: "30"},
                {text:"기니 +224", value: "224"},
                {text:"기니비사우 +245", value: ""},
                {text:"나미비아 +264", value: ""},
                {text:"나우루 +674", value: ""},
                {text:"나이지리아 +234", value: ""},
                {text:"남극,오스트레일리아의외 +672", value: ""},
                {text:"남아프리카공화국 +27", value: ""},
                {text:"네덜란드 +31", value: ""},
                {text:"네덜란드령보네르 +599", value: ""},
                {text:"네덜란드령아루바 +297", value: ""},
                {text:"네팔 +977", value: ""},
                {text:"노르웨이 +47", value: ""},
                {text:"뉴질랜드 +64", value: ""},
                {text:"뉴질랜드령니우에 +683", value: ""},
                {text:"뉴질랜드령토켈라우제도 +690", value: ""},
                {text:"니제르 +227", value: ""},
                {text:"니카라과 +505", value: ""},
                {text:"대한민국 +82", value: "82"},
                {text:"덴마크 +45", value: ""},
                {text:"덴마크령그린란드 +299", value: ""},
                {text:"덴마크령페로제도 +298", value: ""},
                {text:"도미니카공화국 +1 809", value: ""},
                {text:"도미니카공화국 2 +1 829", value: ""},
                {text:"도미니카공화국 3 +1 849", value: ""},
                {text:"독일 +49", value: ""},
                {text:"동티모르 +670", value: ""},
                {text:"라오스 +856", value: ""},
                {text:"라이베리아 +231", value: ""},
                {text:"라트비아 +371", value: ""},
                {text:"러시아/카자흐스탄 +7", value: ""},
                {text:"레바논 +961", value: ""},
                {text:"레소토 +266", value: ""},
                {text:"루마니아 +40", value: ""},
                {text:"룩셈부르크 +352", value: ""},
                {text:"르완다 +250", value: ""},
                {text:"리비아 +218", value: ""},
                {text:"리투아니아 +370", value: ""},
                {text:"리히텐슈타인 +423", value: ""},
                {text:"마다가스카르 +261", value: ""},
                {text:"마셜제도공화국 +692", value: ""},
                {text:"마이크로네시아연방 +691", value: ""},
                {text:"마카오 +853", value: ""},
                {text:"마케도니아공화국 +389", value: ""},
                {text:"말라위 +265", value: ""},
                {text:"말레이시아 +60", value: ""},
                {text:"말리 +223", value: ""},
                {text:"멕시코 +52", value: ""},
                {text:"모나코 +377", value: ""},
                {text:"모로코 +212", value: ""},
                {text:"모리셔스 +230", value: ""},
                {text:"모리타니아 +222", value: ""},
                {text:"모잠비크 +258", value: ""},
                {text:"몬테네그로 +382", value: ""},
                {text:"몰도바 +373", value: ""},
                {text:"몰디브 +960", value: ""},
                {text:"몰타 +356", value: ""},
                {text:"몽골 +976", value: ""},
                {text:"미국/캐나다 +1", value: ""},
                {text:"미국령북마리아나제도 +1 670", value: ""},
                {text:"미얀마 +95", value: ""},
                {text:"바누아투 +678", value: ""},
                {text:"바레인 +973", value: ""},
                {text:"바베이도스 +1 246", value: ""},
                {text:"바하마 +1 242", value: ""},
                {text:"방글라데시 +880", value: ""},
                {text:"베냉 +229", value: ""},
                {text:"베네수엘라 +58", value: ""},
                {text:"베트남 +84", value: ""},
                {text:"벨기에 +32", value: ""},
                {text:"벨라루스 +375", value: ""},
                {text:"벨리즈 +501", value: ""},
                {text:"보스니아헤르체고비나 +387", value: ""},
                {text:"보츠와나 +267", value: ""},
                {text:"볼리비아 +591", value: ""},
                {text:"부룬디 +257", value: ""},
                {text:"부르키나파소 +226", value: ""},
                {text:"부탄 +975", value: ""},
                {text:"불가리아 +359", value: ""},
                {text:"브라질 +55", value: ""},
                {text:"브루나이 +673", value: ""},
                {text:"사모아 +685", value: ""},
                {text:"사우디아라비아 +966", value: ""},
                {text:"산마리노 +378", value: ""},
                {text:"상투메프린시페 +239", value: ""},
                {text:"세네갈 +221", value: ""},
                {text:"세르비아 +381", value: ""},
                {text:"세이셀 +248", value: ""},
                {text:"세인트빈센트그레나딘 +1 784", value: ""},
                {text:"소말리아 +252", value: ""},
                {text:"솔로몬제도 +677", value: ""},
                {text:"수단 +249", value: ""},
                {text:"수리남 +597", value: ""},
                {text:"스리랑카 +94", value: ""},
                {text:"스와질랜드 +268", value: ""},
                {text:"스웨덴 +46", value: ""},
                {text:"스위스 +41", value: ""},
                {text:"스페인 +34", value: ""},
                {text:"슬로바키아 +421", value: ""},
                {text:"슬로베니아 +386", value: ""},
                {text:"시리아 +963", value: ""},
                {text:"시에라리온 +232", value: ""},
                {text:"싱가포르 +65", value: ""},
                {text:"아랍에미리트 +971", value: ""},
                {text:"아르메니아 +374", value: ""},
                {text:"아르헨티나 +54", value: ""},
                {text:"아메리칸사모아 +1 684", value: ""},
                {text:"아이슬란드 +354", value: ""},
                {text:"아이티 +509", value: ""},
                {text:"아일랜드 +353", value: ""},
                {text:"아제르바이잔 +994", value: ""},
                {text:"아프가니스탄 +93", value: ""},
                {text:"안도라 +376", value: ""},
                {text:"알바니아 +355", value: ""},
                {text:"알제리 +213", value: ""},
                {text:"앙골라 +244", value: ""},
                {text:"에디오피아 +251", value: ""},
                {text:"에리트레아 +291", value: ""},
                {text:"에스토니아 +372", value: ""},
                {text:"에콰도르 +593", value: ""},
                {text:"엘살바도르 +503", value: ""},
                {text:"영국 +44", value: ""},
                {text:"영국령세인트헬레나 +290", value: ""},
                {text:"영국령인도양지역 +246", value: ""},
                {text:"영국령지브롤터 +350", value: ""},
                {text:"영국령포클랜드제도 +500", value: ""},
                {text:"예멘 +967", value: ""},
                {text:"오만 +968", value: ""},
                {text:"오스트리아 +43", value: ""},
                {text:"온두라스 +504", value: ""},
                {text:"요르단 +962", value: ""},
                {text:"우간다 +256", value: ""},
                {text:"우루과이 +598", value: ""},
                {text:"우즈베키스탄 +998", value: ""},
                {text:"우크라이나 +380", value: ""},
                {text:"이라크 +964", value: ""},
                {text:"이란 +98", value: ""},
                {text:"이스라엘 +972", value: ""},
                {text:"이집트 +20", value: ""},
                {text:"이탈리아 +39", value: ""},
                {text:"인도 +91", value: ""},
                {text:"인도네시아 +62", value: ""},
                {text:"일본 +81", value: ""},
                {text:"자메이카 +1 876", value: ""},
                {text:"잠비아 +260", value: ""},
                {text:"적도기니 +240", value: ""},
                {text:"조지아 +995", value: ""},
                {text:"중국 +86", value: ""},
                {text:"중앙아프리카공화국 +236", value: ""},
                {text:"지부티 +253", value: ""},
                {text:"짐바브웨 +263", value: ""},
                {text:"차드 +235", value: ""},
                {text:"체코 +420", value: ""},
                {text:"칠레 +56", value: ""},
                {text:"카메룬 +237", value: ""},
                {text:"카보베르데 +238", value: ""},
                {text:"카타르 +974", value: ""},
                {text:"캄보디아왕국 +855", value: ""},
                {text:"케냐 +254", value: ""},
                {text:"코모로,마요트 +269", value: ""},
                {text:"코스타리카 +506", value: ""},
                {text:"코트디부아르 +225", value: ""},
                {text:"콜롬비아 +57", value: ""},
                {text:"콩고 +242", value: ""},
                {text:"콩고민주공화국 +243", value: ""},
                {text:"쿠바 +53", value: ""},
                {text:"쿠웨이트 +965", value: ""},
                {text:"쿡제도 +682", value: ""},
                {text:"크로아티아 +385", value: ""},
                {text:"키르기스스탄 +996", value: ""},
                {text:"키리바시 +686", value: ""},
                {text:"키프로스 +357", value: ""},
                {text:"타이완 +886", value: ""},
                {text:"타지키스탄 +992", value: ""},
                {text:"탄자니아 +255", value: ""},
                {text:"태국 +66", value: ""},
                {text:"터키 +90", value: ""},
                {text:"토고 +228", value: ""},
                {text:"통가 +676", value: ""},
                {text:"투르크메니스탄 +993", value: ""},
                {text:"튀니지 +216", value: ""},
                {text:"트리니다드토바고 +1 868", value: ""},
                {text:"파나마 +507", value: ""},
                {text:"파라과이 +595", value: ""},
                {text:"파키스탄 +92", value: ""},
                {text:"파푸아뉴기니 +675", value: ""},
                {text:"팔라우 +680", value: ""},
                {text:"팔레스타인 +970", value: ""},
                {text:"페루 +51", value: ""},
                {text:"포르투갈 +351", value: ""},
                {text:"폴란드 +48", value: ""},
                {text:"푸에르토리코 +1 787", value: ""},
                {text:"프랑스 +33", value: ""},
                {text:"프랑스령과들루프 +590", value: ""},
                {text:"프랑스령기아나 +594", value: ""},
                {text:"프랑스령뉴칼레도니아 +687", value: ""},
                {text:"프랑스령레위니옹 +262", value: ""},
                {text:"프랑스령마르티니크 +596", value: ""},
                {text:"프랑스령생피에르미클롱 +508", value: ""},
                {text:"프랑스령월리스푸투나제 +681", value: ""},
                {text:"프랑스령폴리네시아 +689", value: ""},
                {text:"피지 +679", value: ""},
                {text:"핀란드 +358", value: ""},
                {text:"필리핀 +63", value: ""},
                {text:"헝가리 +36", value: ""},
                {text:"호주 +61", value: "61"},
                {text:"홍콩 +852", value: "852"}
            ]
        }
    }
}
</script>
